'use strict';
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const read = (rel) => fs.readFileSync(path.join(root, rel), 'utf8');
const route = read('routes/picking.js');
const model = read('services/readModels/pickingQueueStatsReadModel.js');
const presentation = read('services/sessionPresentation.js');
const checks = [];
const check = (name, ok) => checks.push({ name, ok: Boolean(ok) });
check('queue route delegates to read model', route.includes('buildPickingQueueStatsReadModel({'));
check('legacy countOrderedPositions helper removed', !route.includes('async function countOrderedPositions'));
check('task counters use one aggregation', (model.match(/PickingTask\.aggregate\(/g) || []).length === 1);
check('task hot path scans pending/locked only', model.includes("status: { $in: ['pending', 'locked'] }"));
check('order existence and positions share one facet aggregation', (model.match(/Order\.aggregate\(/g) || []).length === 1 && model.includes('$facet'));
check('group is loaded once in queue read model', (model.match(/DeliveryGroup\.findById\(/g) || []).length === 1);
check('current session id resolved once', (model.match(/findCurrentSessionId\(/g) || []).length === 1);
check('session detail loaded once', (model.match(/OrderingSession\.findById\(/g) || []).length === 1);
check('preloaded active-order fact feeds canonical phase', model.includes('activeOrderExists: orderStats.activeOrderExists'));
check('canonical phase can consume preloaded active-order fact', presentation.includes("else if (typeof activeOrderExists === 'boolean')"));
check('orderedPositions failure remains best-effort', model.includes('return { activeOrderExists: null, orderedPositions: 0 }'));
for (const row of checks) console.log(`${row.ok ? 'PASS' : 'FAIL'} ${row.name}`);
const failed = checks.filter((row) => !row.ok);
console.log(`\n${checks.length - failed.length}/${checks.length} PASS`);
if (failed.length) process.exit(1);
