'use strict';
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const read = (rel) => fs.readFileSync(path.join(root, rel), 'utf8');
const catalog = read('services/readModels/deliveryGroupCatalogReadModel.js');
const presentation = read('services/sessionPresentation.js');
const checks = [];
const check = (name, ok) => checks.push({ name, ok: Boolean(ok) });
check('catalog uses batch group presentation', catalog.includes('getCurrentGroupPresentations(groups, { now })'));
check('catalog has no per-group presentation Promise.all', !catalog.includes('Promise.all(groups.map((group) => getCurrentGroupPresentation'));
check('relocated-order flag uses distinct ids, not document hydration', catalog.includes("Order.distinct('buyerSnapshot.deliveryGroupId'"));
check('batch presentation loads sessions in one query', (presentation.match(/OrderingSession\.find\(/g) || []).length >= 1 && presentation.includes('{ $or: clauses }'));
check('batch active-order work uses one aggregation', presentation.includes('activeOrderSessions') && presentation.includes("$group: {\n              _id: {"));
check('batch completed fallback uses one aggregation', presentation.includes('legacyCompletedSessionIds') && presentation.includes('completedTaskSessions'));
check('active-order group identity is preserved', presentation.includes("`${sessionId}|${groupId}`"));
for (const row of checks) console.log(`${row.ok ? 'PASS' : 'FAIL'} ${row.name}`);
const failed = checks.filter((row) => !row.ok);
console.log(`\n${checks.length - failed.length}/${checks.length} PASS`);
if (failed.length) process.exit(1);
