'use strict';
const fs = require('fs');
const path = require('path');
const root = path.join(__dirname, '..');
const read = (rel) => fs.readFileSync(path.join(root, rel), 'utf8');
const checks = [];
const assert = (v, m) => { if (!v) throw new Error(m); };
const check = (n, fn) => { try { fn(); checks.push([n, true]); } catch (e) { checks.push([n, false, e.message]); } };
const model = read('models/CommerceStockReservation.js');
const state = read('models/CommerceStockReservationState.js');
const reservations = read('services/commerce/stockReservations.js');
const stock = read('services/commerce/allegroStockSync.js');
const preview = read('services/commerce/publicationPreview.js');
const route = read('routes/commerce.js');
const registry = read('services/commerce/integrationRegistry.js');
check('provider-neutral reservation model', () => { assert(model.includes("['reserved', 'consumed', 'released', 'unknown']"), 'states missing'); assert(model.includes('countsAgainstStock'), 'hold flag missing'); });
check('no customer PII in reservation schema', () => { assert(!/\b(?:buyer|delivery_fullname|phone|email|payment_done|invoice)\s*:/i.test(model), 'PII-like field leaked'); });
check('epoch prevents historical sent backfill', () => { assert(state.includes('startedAt'), 'epoch missing'); assert(reservations.includes("orderSortDate: { $gte: startedAt }"), 'Allegro epoch missing'); assert(reservations.includes('sentAt: { $gte: startedAt }'), 'BL epoch missing'); });
check('direct Allegro wins aggregator bridge', () => { assert(reservations.includes('sourcePriority: 100'), 'direct priority missing'); assert(reservations.includes('sourcePriority: 70'), 'bridge priority missing'); });
check('exact match ladder and ambiguity gates', () => { assert(reservations.includes("matchStrategy: 'listing_offer_id'"), 'offer match missing'); assert(reservations.includes("matchStrategy: 'sku'"), 'sku missing'); assert(reservations.includes("matchStrategy: 'ean'"), 'ean missing'); assert(reservations.includes('mapping_ambiguous'), 'ambiguity gate missing'); });
check('reservations subtract before channel policy', () => { assert(preview.includes('physicalSource - reservedUnits'), 'central subtraction missing'); assert(preview.indexOf('physicalSource - reservedUnits') < preview.indexOf('source - buffer'), 'reservation must precede buffer'); });
check('3D.6B preview uses live ledger but zero provider writes', () => { assert(stock.includes("stage: '3D.6B'"), 'stage missing'); assert(stock.includes('reservationLedgerReady: true'), 'ledger not live'); assert(stock.includes('inventoryConsumptionReady: false'), 'consumption gate missing'); assert(stock.includes('providerWriteCalls: 0'), 'write counter not zero'); assert(route.includes("'/publications/allegro/stock-sync/preview'"), 'preview route missing'); });
check('registry live ledger / planned stock write', () => { const l = registry.split('\n').find((line) => line.includes("id: 'inventory.reservations'")); const w = registry.split('\n').find((line) => line.includes("id: 'offers.stock.write'") && line.includes('offer-bulk-modification-commands')); assert(l?.includes('implementation: LIVE'), 'ledger not live'); assert(w?.includes('implementation: PLANNED'), 'stock write must stay planned'); });
for (const [n, ok, m] of checks) console.log(`${ok ? 'PASS' : 'FAIL'} ${n}${m ? ` — ${m}` : ''}`);
const failed = checks.filter(([, ok]) => !ok);
console.log(`Commerce Publication Stage 3D.6B backend: ${checks.length-failed.length}/${checks.length} PASS`);
if (failed.length) process.exit(1);
