'use strict';
const fs = require('fs');
const path = require('path');
const root = path.join(__dirname, '..');
const read = (rel) => fs.readFileSync(path.join(root, rel), 'utf8');
const checks = [];
const assert = (v, m) => { if (!v) throw new Error(m); };
const check = (n, fn) => { try { fn(); checks.push([n, true]); } catch (e) { checks.push([n, false, e.message]); } };
const service = read('services/commerce/allegroOfferContentUpdate.js');
const preview = read('services/commerce/allegroOfferUpdatePreview.js');
const route = read('routes/commerce.js');
const registry = read('services/commerce/integrationRegistry.js');
check('minimal PATCH only', () => { assert(service.includes("method: 'PATCH'"), 'PATCH missing'); assert(service.includes('body: patch'), 'patch body missing'); });
check('fresh preview gate', () => { assert(service.includes('previewAllegroOfferUpdate'), 'preview gate missing'); assert(service.includes('mappingChangeCount'), 'mapping gate missing'); });
check('no price or stock in content patch', () => { assert(!preview.includes('contentPatch.sellingMode'), 'price leaked'); assert(!preview.includes('contentPatch.stock'), 'stock leaked'); });
check('durable 202/unknown recovery', () => { assert(service.includes('providerOperationPath'), 'operation missing'); assert(service.includes('recoverUnknown'), 'recovery missing'); assert(service.includes("retryPolicy: 'never'"), 'blind retry risk'); });
check('readback verification', () => { assert(service.includes('contentPatchIssues(patch, offer)'), 'readback verification missing'); });
check('single command route', () => { assert(route.includes("'/publications/allegro/update-content'"), 'route missing'); assert(!route.includes("'/publications/allegro/update-content/status'"), 'redundant status route'); });
check('registry live', () => { assert(registry.includes("id: 'offers.update'"), 'registry missing'); assert(registry.includes('safe contentPatch'), 'registry not updated'); });
check('price stock still planned', () => { assert(registry.includes("id: 'offers.price.write'"), 'price missing'); assert(registry.includes("id: 'offers.stock.write'"), 'stock missing'); });
for (const [n, ok, m] of checks) console.log(`${ok ? 'PASS' : 'FAIL'} ${n}${m ? ` — ${m}` : ''}`);
const failed = checks.filter(([,ok]) => !ok);
console.log(`Commerce Publication Stage 3D.4.1 backend: ${checks.length-failed.length}/${checks.length} PASS`);
if (failed.length) process.exit(1);
