'use strict';
const fs = require('fs');
const path = require('path');
const root = path.join(__dirname, '..');
const read = (rel) => fs.readFileSync(path.join(root, rel), 'utf8');
const checks = [];
const assert = (v, m) => { if (!v) throw new Error(m); };
const check = (n, fn) => { try { fn(); checks.push([n, true]); } catch (e) { checks.push([n, false, e.message]); } };
const route = read('routes/commerce.js');
const service = read('services/commerce/allegroStockSync.js');
const preview = read('services/commerce/publicationPolicy.js');
const registry = read('services/commerce/providers/allegro.js');
check('read-only preview route survives later stages', () => { assert(route.includes("'/publications/allegro/stock-sync/preview'"), 'preview missing'); });
check('batched GET by external.id', () => { assert(service.includes("path: '/sale/offers'"), 'GET offers missing'); assert(service.includes("'external.id': part"), 'external id batching missing'); });
check('zero writes until reservations', () => { assert(service.includes('providerWriteCalls: 0'), 'write counter not zero'); assert(!service.includes("method: 'POST'"), 'provider POST leaked into preview'); });
check('zero stock lifecycle is explicit', () => { assert(service.includes('zero_stock_will_end_offer'), 'zero end warning missing'); assert(service.includes('offer_reactivation_required'), 'reopen warning missing'); });
check('Commerce Inventory clamps fixed policy', () => { assert(preview.includes('inventoryOnHand'), 'Commerce Inventory source missing'); assert(preview.includes('Math.min(inherited, requested)'), 'fixed clamp missing'); });
check('preview shows source/policy/actual', () => { assert(service.includes('desiredStock'), 'desired stock missing'); assert(service.includes('actualStock'), 'actual stock missing'); assert(service.includes('buffer: wholeStock'), 'buffer missing'); });
check('registry preview live and stock write separate', () => { const p = registry.split('\n').find((line) => line.includes("id: 'offers.stock.preview'")); const w = registry.split('\n').find((line) => line.includes("id: 'offers.stock.write'") && line.includes('offer-bulk-modification-commands')); assert(p?.includes('implementation: LIVE'), 'preview not live'); assert(Boolean(w), 'stock capability missing'); });
check('price sync remains stock-free', () => { const price = read('services/commerce/allegroPriceSync.js'); const fn = price.slice(price.indexOf('function modificationForJob'), price.indexOf('function isAmbiguous')); assert(!fn.includes('stock:'), 'stock leaked into price stage'); });
for (const [n, ok, m] of checks) console.log(`${ok ? 'PASS' : 'FAIL'} ${n}${m ? ` — ${m}` : ''}`);
const failed = checks.filter(([, ok]) => !ok);
console.log(`Commerce Publication Stage 3D.6A backend: ${checks.length-failed.length}/${checks.length} PASS`);
if (failed.length) process.exit(1);
