'use strict';
const fs = require('fs');
const path = require('path');
const root = path.join(__dirname, '..');
const read = (rel) => fs.readFileSync(path.join(root, rel), 'utf8');
const checks = [];
const assert = (v, m) => { if (!v) throw new Error(m); };
const check = (n, fn) => { try { fn(); checks.push([n, true]); } catch (e) { checks.push([n, false, e.message]); } };
const service = read('services/commerce/allegroPriceSync.js');
const route = read('routes/commerce.js');
const registry = read('services/commerce/integrationRegistry.js');
check('preview + one apply command', () => { assert(route.includes("'/publications/allegro/price-sync/preview'"), 'preview missing'); assert(route.includes("'/publications/allegro/price-sync'"), 'apply missing'); assert(!route.includes("'/publications/allegro/price-sync/status'"), 'redundant status route'); });
check('current Allegro beta bulk contract', () => { assert(service.includes("'/sale/offer-bulk-modification-commands'"), 'bulk endpoint missing'); assert(service.includes('application/vnd.allegro.beta.v1+json'), 'beta media type missing'); assert(service.includes('const BULK_LIMIT = 25'), '25 limit missing'); });
check('per-offer FIXED price only', () => { const fn = service.slice(service.indexOf('function modificationForJob'), service.indexOf('function isAmbiguous')); assert(fn.includes("changeType: 'FIXED'"), 'FIXED price missing'); assert(fn.includes('prices: {'), 'prices missing'); assert(!fn.includes('stock:'), 'stock leaked into 3D.5'); });
check('batched preview sees price automation', () => { assert(service.includes("'external.id': part"), 'external.id batch lookup missing'); assert(service.includes('priceAutomationRule'), 'automation detection missing'); });
check('automation override is explicit', () => { assert(service.includes('allowDisablePriceAutomation'), 'confirmation flag missing'); assert(service.includes('automation_confirmation_required'), 'confirmation gate missing'); });
check('durable command and no blind POST retry', () => { assert(service.includes('await setJobsCommand(jobs, commandId)'), 'command not persisted first'); assert(service.includes("retryPolicy: 'never'"), 'blind retry risk'); assert(service.includes('maxAttempts: 1'), 'POST attempts unsafe'); });
check('same command recovery + 409', () => { assert(service.includes('retryUnknownCommand(group.accountId, group.commandId, group.jobs)'), 'same command retry missing'); assert(service.includes('upstreamStatus === 409'), '409 recovery missing'); assert(service.includes('unknown_stale_desired'), 'stale replay guard missing'); });
check('unresolved recovery happens before fresh writes', () => { assert(service.includes('Recovery always comes first'), 'recovery ordering missing'); assert(service.includes('unresolvedListingIds'), 'unresolved listing guard missing'); });
check('tasks + read-back verification', () => { assert(service.includes("=== 'prices'"), 'price task filter missing'); assert(service.includes('verifySuccessfulJobs'), 'readback verify missing'); assert(service.includes('samePrice(storedDesired, row.actualPrice)'), 'actual price verify missing'); });
check('registry price live stock planned', () => { assert(registry.includes("id: 'offers.price.write'"), 'price registry missing'); assert(registry.includes('Stage 3D.5'), 'price stage missing'); const stockLine = registry.split('\n').find((line) => line.includes("id: 'offers.stock.write'") && line.includes("label: 'Синхронізація залишку'")); assert(stockLine?.includes('implementation: PLANNED'), 'stock must remain planned'); });
for (const [n, ok, m] of checks) console.log(`${ok ? 'PASS' : 'FAIL'} ${n}${m ? ` — ${m}` : ''}`);
const failed = checks.filter(([,ok]) => !ok);
console.log(`Commerce Publication Stage 3D.5 backend: ${checks.length-failed.length}/${checks.length} PASS`);
if (failed.length) process.exit(1);
